version: '3'

services:
  resume-generator:
    build: .
    volumes:
      # Mount the project root to /app in the container
      - ./:/app
    environment:
      - OUTPUT_DIR=/app
    # Override the entrypoint to keep the container running
    entrypoint: ["tail", "-f", "/dev/null"]
    # Container name for easy reference
    container_name: resume-generator
    # The container will automatically run generate_resume.py via ENTRYPOINT 